/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicaFinal;

/**
 *representa una clase interna ,extiende de javax.swing.JInternalFrame 
 * @author Bogdan Alin Muresan
 * @version 1.0
 * 
 * 
 */
public class VentanaInterna extends javax.swing.JInternalFrame 
{
    public VentanaPaint padre=new VentanaPaint();
    
    public VentanaInterna() {
        initComponents();
  
    }
    /**
     * Creates new form VentanaInterna
     * @param nuevoPadre
     */
    public VentanaInterna(VentanaPaint nuevoPadre) {
        initComponents();
        padre=nuevoPadre;
        //lienzo2DImage.setPadreLienzo(nuevoPadre);
    }
    
    /**
     * metodo selector que devuele el padre
     * @return padre
     */
    public VentanaPaint  getPadre()
    {
        return padre;
    }
    
    /**
     * metodo modificador que modifica el padre
     * @param padrenuevo
     */
    public  void setPadre(VentanaPaint padrenuevo )
    {
        padre=padrenuevo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneLienzo2DImage = new javax.swing.JScrollPane();
        lienzo2DImage = new sm.bam.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
        });

        lienzo2DImage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DImageMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DImageLayout = new javax.swing.GroupLayout(lienzo2DImage);
        lienzo2DImage.setLayout(lienzo2DImageLayout);
        lienzo2DImageLayout.setHorizontalGroup(
            lienzo2DImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        lienzo2DImageLayout.setVerticalGroup(
            lienzo2DImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jScrollPaneLienzo2DImage.setViewportView(lienzo2DImage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneLienzo2DImage)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPaneLienzo2DImage)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo que reestablece el estado anterior de la ventana
     * @param evt 
     */
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
                                          
        // TODO add your handling code here:
        //restauramos el estado del lienzo
       padre.setEditarActivo(getLienzo().getEditar());
       padre.setAlisarActivo(getLienzo().getHayRenderizacion());
       padre.setTransparenciaActivo(getLienzo().getHayComposicion());
       padre.setRellenoActivo(getLienzo().getRelleno());
       
       padre.setBotonFormaActiva(getLienzo().getForma());
       padre.setColorActivo(getLienzo().getColor());
       padre.setSpinnerGrosor(getLienzo().getSpinner());
    }//GEN-LAST:event_formInternalFrameActivated

    /**
     * metodo que guarda el estado actual ,antes de ser desactivada
     * @param evt 
     */
    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated

        //guardamos estado del lienzo
       getLienzo().setHayRenderizacion(padre.getAlisarActivo());
       getLienzo().setEditar(padre.getEditarActivo());
       getLienzo().setRelleno(padre.getRellenoActivo());
       getLienzo().setHayComposicion(padre.getTransparenciaActivo());
      
       getLienzo().setForma(padre.getBotonFormaActiva());
       getLienzo().setColor(padre.getColorActivo());
       getLienzo().setSpinner(padre.getSpinnerGrosor());
    }//GEN-LAST:event_formInternalFrameDeactivated

    /**
     * metodo que toma la posicion del raton en el lienzo
     * @param evt 
     */
    private void lienzo2DImageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImageMouseMoved
        // TODO add your handling code here:
        //getPadre().mousePosition.setText("("+MouseInfo.getPointerInfo().getLocation().x+", "+MouseInfo.getPointerInfo().getLocation().y+")");
       getPadre().mousePosition.setText("("+evt.getPoint().getX()+", "+evt.getPoint().getY()+")");

    }//GEN-LAST:event_lienzo2DImageMouseMoved

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneLienzo2DImage;
    private sm.bam.iu.Lienzo2DImagen lienzo2DImage;
    // End of variables declaration//GEN-END:variables

    /**
     * metodo selector que devuelve el lienzo
     * @return Lienzo2DImage
     */
    public sm.bam.iu.Lienzo2DImagen getLienzo()
{
    return lienzo2DImage;
}
    
    public void setAtributos(){
        //forma activa
        getLienzo().setForma(padre.getBotonFormaActiva());
        //grosor trazo
        getLienzo().setSpinner(padre.getSpinnerGrosor());
        //editar
        getLienzo().setEditar(padre.getEditarActivo());
        //alisar
        getLienzo().setHayRenderizacion(padre.getAlisarActivo());
        //relleno
        getLienzo().setRelleno(padre.getRellenoActivo());
        //transparencia
        getLienzo().setRelleno(padre.getRellenoActivo());
        //color activo
        getLienzo().setColor(padre.getColorActivo());
        //
    }
    
}//final clase
