/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sm.bam.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import practicaFinal.VentanaInterna;
import practicaFinal.VentanaPaint;



/**
 *
 * @author bogdan
 */
public class Lienzo2DImagen extends Lienzo2D {
   private BufferedImage img;
   
    /**
     * Creates new form Lienzo2dImagen
     */
    public Lienzo2DImagen() {
        initComponents();
    }

    public Lienzo2DImagen(VentanaInterna aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    
    /**
     * metodo que pinta una imagen
     * @param g 
     * @see BufferedImage
     */
    @Override
     public void paintComponent(Graphics g){
        super.paintComponent(g);
        //Graphics2D g2d=(Graphics2D)g;
        //g2d=img.createGraphics();
        if(img!=null) g.drawImage(img,0,0,this);
     }
    /**
     * metodo modificador 
     * @param img 
     */
    public void setImage(BufferedImage img){
        this.img = img;
        if(img!=null) {
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }
           
    /**
     * metodo selector 
     * @return  img 
     */
    public BufferedImage getImage(){
        return img;
    }
    /**
     * devuelve la imagen con todas la formas dibujadas sobre ella
     * @param drawVector
     * @return devuelve la imagen
     */
    public BufferedImage getImage(boolean drawVector){
        // TODO: Código para crear una nueva imagen
        //       que contenga la imagen actual más
        //       las formas
        if (drawVector) {
            BufferedImage img_tmp;
            img_tmp=new BufferedImage(img.getWidth(),img.getHeight(),img.getType());
            Graphics2D mig2d=(Graphics2D)img_tmp.getGraphics();
            mig2d.drawImage(img, 0, 0, null);
            super.paint(mig2d);
           
        return img_tmp;
        }
            
        else{
               return getImage();
           }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setVentanaInterna(VentanaInterna aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setVentanaInterna(VentanaInterna aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setVentanaInterna(VentanaInterna aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setVentanaInterna(VentanaInterna aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setVentanaInterna(VentanaPaint nuevoPadre) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
